import { Building2, CheckCircle2, Search, ShieldX, UserCheck, UsersRound } from "lucide-react";

import { reviewWholesaleAccountAction } from "@/app/app/tienda/actions";
import { dateTime } from "@/lib/format";
import { getCurrentOrganization } from "@/lib/data/current-organization";
import { createServerSupabaseClient } from "@/lib/supabase/server";

export const dynamic = "force-dynamic";
const labels: Record<string, string> = { not_requested: "Minorista", pending: "Pendiente", approved: "Aprobado", rejected: "Rechazado", suspended: "Suspendido" };

export default async function WholesaleAccountsPage({ searchParams }: { searchParams: Promise<{ buscar?: string; estado?: string }> }) {
  const supabase = await createServerSupabaseClient(); const organization = await getCurrentOrganization(supabase); if (!organization) return null;
  if (organization.role === "staff") return <div className="page-container permission-state"><UsersRound /><h1>Acceso restringido</h1><p>Las cuentas mayoristas están disponibles para dueños y administradores.</p></div>;
  const params = await searchParams; const search = params.buscar?.trim() ?? ""; const status = params.estado ?? "pending";
  let query = supabase.from("store_customer_profiles").select("*").eq("organization_id", organization.id).order("created_at", { ascending: false });
  if (status !== "all") query = query.eq("wholesale_status", status as never);
  if (search) query = query.or(`first_name.ilike.%${search}%,last_name.ilike.%${search}%,email.ilike.%${search}%,business_name.ilike.%${search}%`);
  const { data: profiles, error } = await query; if (error) throw new Error("No se pudieron cargar las cuentas.");
  return <div className="page-container"><header className="page-header"><div><span className="eyebrow">Tienda online</span><h1 className="page-title mt-2">Cuentas mayoristas</h1><p className="page-lead">Revisá solicitudes y controlá quién puede consultar precios mayoristas protegidos.</p></div></header><form className="filter-bar"><label className="search-field"><Search /><input defaultValue={search} name="buscar" placeholder="Nombre, correo o comercio" /></label><select className="field-input" defaultValue={status} name="estado"><option value="pending">Pendientes</option><option value="approved">Aprobadas</option><option value="rejected">Rechazadas</option><option value="suspended">Suspendidas</option><option value="all">Todas</option></select><button className="button button-secondary" type="submit">Filtrar</button></form><section className="wholesale-admin-grid">{profiles?.length ? profiles.map((profile) => <article className="wholesale-admin-card" key={profile.user_id}><div className="wholesale-admin-heading"><span className="summary-strip-icon"><Building2 /></span><div><strong>{profile.first_name} {profile.last_name}</strong><small>{profile.business_name ?? "Sin comercio informado"}</small></div><span className={`web-order-admin-status status-${profile.wholesale_status}`}>{labels[profile.wholesale_status]}</span></div><dl><div><dt>Correo</dt><dd>{profile.email}</dd></div><div><dt>Teléfono</dt><dd><a href={`tel:${profile.phone}`}>{profile.phone}</a></dd></div><div><dt>Ubicación</dt><dd>{profile.locality}, {profile.province}</dd></div>{profile.cuit ? <div><dt>CUIT</dt><dd>{profile.cuit}</dd></div> : null}<div><dt>Solicitud</dt><dd>{dateTime.format(new Date(profile.created_at))}</dd></div></dl><form action={reviewWholesaleAccountAction} className="wholesale-review-form"><input name="user_id" type="hidden" value={profile.user_id} /><label>Nota interna<input className="field-input" defaultValue={profile.wholesale_review_notes ?? ""} name="notes" placeholder="Opcional" /></label><div>{profile.wholesale_status !== "approved" ? <button className="button button-primary" name="status" type="submit" value="approved"><CheckCircle2 /> Aprobar</button> : <button className="button button-secondary" name="status" type="submit" value="suspended"><ShieldX /> Suspender</button>}<button className="button button-secondary" name="status" type="submit" value="rejected"><UserCheck /> Rechazar</button></div></form></article>) : <div className="empty-state"><UsersRound /><h2>No hay cuentas en esta vista</h2><p>Probá con otro estado o término de búsqueda.</p></div>}</section></div>;
}
